version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: university_postgres
    environment:
      POSTGRES_USER: borabln
      POSTGRES_PASSWORD: 20333039362aA_
      POSTGRES_DB: mavisiteproje
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U borabln"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: university_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: bulunbora@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 20333039362aA_
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local